### ISSUE TITLE
Line Next to Icon

### ISSUE THREAD

**Issue by 14schua** [isaac-blasiman/stmartins-guest-attendance#1]
In the Sign-In View, when the left-most person icon is hovered over, a blue underline appears to the right of the person. This only happens when there is another person icon to the right of the problem person icon, and it only happens when the icons are encased in links.

**Comment by isaac-blasiman** [comment]
Once the icons were put into Bootstrap buttons, the line no longer showed up next to the icon when the icon was hovered over.

**Comment by isaac-blasiman** [comment]
Is fixed by issue #6, Fix any remaining major UI issues. Once #6 is merged in, the problem will be gone.
