### ISSUE TITLE
Unused Javascript Call

### ISSUE THREAD

**Issue by MattBabb** [isaac-blasiman/stmartins-guest-attendance#65]
Line 63 of "Create Signature - Adult.html" makes a call to `<script src="signature_pad-master/signature_pad-master/example/js/send-signature-entry.js"></script>` However, there is no file named "send-signature-entry.js" at that location.

**Comment by isaac-blasiman** [comment]
Hi Matt,

I took a quick look at it and you are right - there doesn't seem to be a
"send-signature-entry.js" file at the location in the link. The "send
signature entry" functionality would be sending the signature to the
database, and we didn't finish that part of the functionality.

My hunch is that Andrew or I planned to create the send-signature-entry.js
file at some point but ended up trying another method. (That method
probably didn't work either). So I think it is a dead link. Does that make
sense?

Let me know if you have other questions about this or something else.

- Isaac Blasiman

**Comment by MattBabb** [comment]
Haha, thanks Isaac! Yeah I think I followed that. I figured it was something like that but you saved me some time digging around for it. For future reference, I'll be adding bugs and whatnot to the GitHub because Dr. Hoffert wants me to track things like that and do version management via GitHub. You shouldn't have to worry about looking in to these things as most of them are more or less notes for myself. If I do need some help with past pieces of code I'll reach out to one of you two, but I thought I should let you know that you shouldn't need to make time for most of this, it's just stuff for my project. Thanks for looking in to it! Matt
________________________________

**Comment by isaac-blasiman** [comment]
No problem! Thanks for letting me know.

 - Isaac
